spring.application.name=Creatival_project
#database
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.datasource.url=jdbc:h2:file:./data/local
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

logging.level.org.springframework.security=DEBUG

#jpa
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.show-sql=true

#Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}

spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#file
file.upload-dir=C:/creatival_file/
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=100GB

# íê¸ ê¹¨ì§ ë°©ì§ ì¤ì 
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
server.servlet.encoding.enabled=true

#PortOne
portone.api.key={검열}
portone.api.base-url=https://api.portone.io
portone.api.secret={검열}